version: '2'

services:
    nginx:
      container_name: andino-nginx
      image: datosgobar/portal-base-nginx:release-0.10.2
      restart: always
      ports:
        - "${NGINX_HOST_PORT}:80"
        - "443:443"
      depends_on:
        - portal
      networks:
        portal-network:
          aliases:
            - "${SITE_HOST}"
      environment:
        - NGINX_CONFIG_FILE
        - NGINX_CACHE_MAX_SIZE
        - NGINX_CACHE_INACTIVE
    portal:
      container_name: andino
      image: "datosgobar/portal-andino:${ANDINO_TAG}"
      restart: always
      ports:
        - "${DATASTORE_HOST_PORT}:8800"
      depends_on:
        - db
        - solr
        - redis
        - postfix
      networks:
        - portal-network
      environment:
        - TZ
    db:
      container_name: andino-db
      image: postgres:9.5
      restart: always
      environment:
        - POSTGRES_DB=ckan
        - POSTGRES_USER
        - POSTGRES_PASSWORD
      networks:
        - portal-network
    redis:
      container_name: andino-redis
      image: redis:3.2.7-alpine
      restart: always
      networks:
        - portal-network
    solr:
      container_name: andino-solr
      image: datosgobar/portal-base-solr:release-0.9.0
      restart: always
      networks:
        - portal-network
    postfix:
      container_name: andino-postfix
      image: catatnight/postfix
      restart: always
      environment:
        - smtp_user=portal:portal
        - maildomain
      ports:
        - "25:25"
      networks:
        - portal-network

networks:
  portal-network:
