#!/bin/bash
DHUB_USER="jsalgadowk"
CKAN_DI="ckan"
PG_DI="pg-ckan"
SOLR_DI="solr"


CKAN_APACHE2_PORT="80"
CKAN_DATAPUSHER_PORT="8800"
CKAN_CONFIG_FILE="development.ini"
CKAN_HOME="/usr/lib/ckan/default"
CKAN_CONFIG="/etc/ckan/default"
CKAN_DATA="/var/lib/ckan"


get_ip(){
	echo $(ifconfig $(route | grep '^default' | grep -o '[^ ]*$') | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
}

clear 
printf "\n
╔═════════════════════════════════════════════════════════╗
║                                                         ║
║     BIENVENIDO A LA INSTALACION AUTOMATICA DE CKAN      ║
║                 EN DOCKER RHEL|CENTOS.                  ║
║                                                         ║
╚═════════════════════════════════════════════════════════╝
\n"
# Esta docker insalado?	
if [ $(dpkg-query -W -f='${Status}' docker-engine 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
	# No? no importa, lo instalamos! :D
	echo "Instalando Docker Engine ..."
	curl -sSL https://get.docker.com/ | sh
fi
# Instalemos CKAN! :D
echo "$CKAN_DI $PG_DI $SOLR_DI" | xargs -n 1 | while read img; do docker rm -f $img; done
echo "$CKAN_DI $PG_DI $SOLR_DI" | xargs -n 1 | while read img; do docker pull $DHUB_USER/$img:latest; done
mkdir -p $HOME/ckan/volumenes/data $HOME/ckan/volumenes/config $HOME/ckan/volumenes/pgdata

echo "$PG_DI $SOLR_DI" | xargs -n 1 | while read img; do docker run -d  --name $img $DHUB_USER/$img; done
docker run -d -v $HOME/ckan/volumenes/data:/var/lib/ckan --link $PG_DI:db --link $SOLR_DI:solr -p 80:80 -p 8800:8800 --name $CKAN_DI $DHUB_USER/$CKAN_DI:latest

echo "bindeando CKAN..."
docker exec -it ckan /usr/lib/ckan/default/bin/paster --plugin=ckan config-tool /etc/ckan/default/production.ini -e "ckan.datapusher.url = http://$(get_ip):8800" "ckan.site_url = http://$(get_ip)"	

echo "Creando usuario \"ckan_admin\"..."
echo "Tenes que presionar \"y\" cuando el instalador te pregunte si deseas crear el usuarios y luego, cuando el instalar lo pida, ingresa la contraseña."
docker exec -it ckan /bin/bash -c "/usr/lib/ckan/default/bin/paster --plugin=ckan sysadmin add ckan_admin -c /etc/ckan/default/production.ini"

echo "Esperando reinicio del contenedor..."
sleep 15
docker start ckan
echo "Todo listo!, ya podes contarle a todo el mundo que tenes un CKAN hermoso"